# Generated by Django 4.2.19 on 2025-02-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviereviews', '0002_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.TextField(max_length=100, unique=True),
        ),
    ]
