# Generated by Django 4.2.19 on 2025-02-20 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviereviews', '0004_alter_genre_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='imdb_id',
        ),
    ]
