# Generated by Django 4.2.19 on 2025-02-21 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviereviews', '0007_movie_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='rating',
        ),
    ]
