# Generated by Django 4.2.19 on 2025-02-23 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviereviews', '0009_alter_comment_review_alter_movie_genres'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reaction',
        ),
    ]
